server:
  port: 10001
spring:
  application:
    name: gateway-doc-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: http://localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: provider-service
        url: /v3/api-docs/provider-service
      - name: consumer-service
        url: /v3/api-docs/provider-service
  cache:
    disabled: true
